/**
 * One-off: fetches real street geometry from the public OSRM demo server for every
 * sample vehicle and writes src/data/routes.generated.ts. Run: pnpm routes:generate
 * The demo server is for development only; production routing must use your own service.
 */
import { writeFileSync } from "node:fs"
import { BASE, ORDER_COORDS, VEHICLE_STOPS } from "../src/data/places.ts"

type Coord = [number, number]

async function route(waypoints: Coord[]): Promise<Coord[]> {
  const path = waypoints.map(([lat, lng]) => `${lng},${lat}`).join(";")
  const url = `https://router.project-osrm.org/route/v1/driving/${path}?overview=full&geometries=geojson`
  const res = await fetch(url)
  if (!res.ok) throw new Error(`OSRM ${res.status} for ${path}`)
  const json = (await res.json()) as {
    code: string
    routes: { geometry: { coordinates: [number, number][] } }[]
  }
  if (json.code !== "Ok") throw new Error(`OSRM ${json.code} for ${path}`)
  return json.routes[0].geometry.coordinates.map(([lng, lat]) => [
    Math.round(lat * 1e5) / 1e5,
    Math.round(lng * 1e5) / 1e5,
  ])
}

const out: Record<string, Coord[]> = {}
for (const [vehicle, orders] of Object.entries(VEHICLE_STOPS)) {
  const stops = orders.map((id) => ORDER_COORDS[id])
  out[vehicle] = await route([BASE, ...stops])
  console.log(vehicle, out[vehicle].length, "points")
  await new Promise((r) => setTimeout(r, 1200)) // be gentle with the public server
}

const body = Object.entries(out)
  .map(([k, v]) => `  "${k}": ${JSON.stringify(v)},`)
  .join("\n")
writeFileSync(
  new URL("../src/data/routes.generated.ts", import.meta.url),
  `// Generated by scripts/generate-routes.ts from OSRM (OpenStreetMap data, ODbL). Do not edit.\nexport const ROUTES: Record<string, [number, number][]> = {\n${body}\n}\n`
)
console.log("written")
